version: "3.9"

services: 
  broker: 
    image: nats-streaming
    ports:
      - 4222:4222
  publisher:
    image: "nkzren/publisher"
    build: ./publisher
    ports:
      - 3000:3000
    depends_on: 
      - "broker"
    environment:
      - BROKER_URL=broker
  subscriber:
    image: "nkzren/subscriber"
    build: ./subscriber
    ports:
      - 3001:3000
    environment:
      - MONGO_URL=subscriber_db
      - BROKER_URL=broker
    depends_on: 
      - "broker"
      - "subscriber_db"
  subscriber_db:
    image: mongo
    volumes: 
      - /tmp/data:/data/db
    ports:
    - 27017:27017
