apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app: broker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: nats-streaming
        image: nats-streaming:0.21.2-alpine3.13
        ports:
        - containerPort: 4222

---

apiVersion: v1
kind: Service
metadata:
  name: broker-service
spec:
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
data:
  broker_url: "10.105.208.35"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pubsubs-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST"
spec:
  rules:
    - host: mypubsubs.info
      http:
        paths:
          - path: /web
            pathType: Exact
            backend:
              service:
                name: web
                port:
                  number: 8080
          - path: /publisher(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: publisher-service
                port:
                  number: 3000
          - path: /subscriber(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: subscriber-service
                port:
                  number: 3000
